# nanodet-EfficientNet-Lite0_320
# COCO mAP(0.5:0.95) = 0.247
#             AP_50  = 0.404
#             AP_75  = 0.250
#           AP_small = 0.079
#               AP_m = 0.243
#               AP_l = 0.406
save_dir: workspace/nanodet_flops
model:
  arch:
    name: ComputeFlops
    backbone:
      #name: ResNet
      #depth: 18
      #out_stages: [2, 3, 4]
      #activation: LeakyReLU
      name: MobileNetV2
      width_mult: 1.0
      out_stages: [ 2, 4, 6 ]
      last_channel: 1280
      activation: LeakyReLU

data:
  train:
    name: CocoDataset
    img_path: /root/deng/dataset/coco/mine/train/person_cat_dog
    ann_path: /root/deng/dataset/coco/mine/train/person_cat_dog.json
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
  val:
    name: CocoDataset
    img_path: /root/deng/dataset/coco/mine/val/person_cat_dog
    ann_path: /root/deng/dataset/coco/mine/val/person_cat_dog_val.json
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
device:
  gpu_ids: [0, 1]
  workers_per_gpu: 10
  batchsize_per_gpu: 96
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.15
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 500
    ratio: 0.01
  total_epochs: 80
  lr_schedule:
    name: MultiStepLR
    milestones: [140,170,180,185]
    gamma: 0.1
  val_intervals: 5
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10


class_names: ['person', 'cat', 'dog']
